name: Deploy SIAGA Admin Web (Prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ⬇️ ENV DIBUAT SEBELUM BUILD
      - name: Generate production env
        run: |
          cat <<EOF > .env.production
          NEXT_PUBLIC_API_BASE_URL=https://api.siaga.click
          EOF

      - name: Upload source
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/farid/siaga/siaga-admin-web"
          strip_components: 1

      - name: Deploy & switch Admin Web
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/farid/siaga/infra
            ./deploy-and-switch-service.sh siaga-admin